import config from "../config.js";
import { ephemeralEmbed } from "../utils/responses.js";

function createEmbed(description) {
    return {
        description,
        color: config.color.default,
    };
}

const tosEmbeds = {
    service_information: createEmbed(
        "•    **Nama Usaha:** Harmony Hub\n•    **Jenis Usaha:** Jasa Pengembangan Digital\n•    **Pengelola:** Tokioshy\n•    **Kontak:** harmonyhub.id@gmail.com",
    ),
    definition_and_service: createEmbed(
        "## Definisi Istilah Kunci\n•    **Karya Akhir:** hasil akhir dari layanan pengembangan yang disepakati, termasuk namun tidak terbatas pada source code, aplikasi, software, konfigurasi server, aset digital, dan dokumentasi.\n•    **SOW (Scope of Work):** ruang lingkup pekerjaan yang disepakati, mencakup fitur, spesifikasi teknis, batasan proyek, serta target waktu penyelesaian.\n•    **Revisi Minor:** perbaikan tampilan atau penyesuaian estetika ringan yang tidak menambah fitur baru dan tidak mengubah alur kerja yang telah disepakati dalam SOW. Tidak termasuk kesalahan logika kode (lihat Pasal Dukungan Purnajual Gratis).\n•    **Perubahan Scope (Major Change):** penambahan fitur, perubahan alur kerja, atau penyesuaian signifikan yang tidak tercantum dalam SOW awal.\n## Rincian Layanan\nHarmony Hub menyediakan jasa pengembangan dan konfigurasi digital sesuai dengan spesifikasi yang diminta oleh Klien. Layanan utama meliputi:\n•    **Pengembangan Karya Akhir Kustom:** pembuatan aplikasi, bot, atau perangkat lunak kustom dengan fitur sesuai permintaan.\n•    **Konfigurasi Lingkungan Digital:** pembuatan dan konfigurasi server (seperti Discord), template platform, atau ekosistem digital lainnya.\n•   **Integrasi dan Instalasi:** pemasangan dan pengaturan Karya Akhir pada server, hosting, atau platform milik Klien.\n•    **Dukungan Purnajual:** penyediaan dukungan teknis pasca-penyerahan karya (sesuai paket atau perjanjian tambahan).\n•   **Konsultasi:** jasa konsultasi terkait penggunaan, pemeliharaan, optimalisasi, dan pengembangan digital lainnya.",
    ),
    tos_service: createEmbed(
        "## Proses Pemesanan dan Perjanjian Kerja\n•    **Pemberian Brief:** Klien wajib memberikan deskripsi teknis yang jelas dan lengkap mengenai kebutuhan proyek sebelum pengerjaan dimulai.\n•    **Penawaran dan Persetujuan:** Kami akan memberikan Penawaran Harga (*Quotation*), estimasi waktu, dan SOW yang rinci.\n•    **Keterikatan Kontrak:** Pengerjaan dimulai hanya setelah Klien menyetujui Penawaran Harga secara tertulis. Persetujuan ini berlaku sebagai kontrak yang mengikat secara hukum.\n•    **Biaya Perubahan Scope:** Perubahan Scope (*Major Change*, lihat Pasal Definisi Istilah Kunci) setelah proyek berjalan wajib disepakati ulang dan akan dikenakan biaya tambahan (*change request fee*) serta penyesuaian jadwal penyelesaian.\n## Akses dan Kerjasama Klien\n•    **Penyediaan Akses:** Klien bertanggung jawab penuh untuk menyediakan informasi, akses sementara (izin administrator, token, API key), dan aset yang diperlukan untuk penyelesaian proyek.\n•    **Akurasi Informasi:** Klien menjamin bahwa seluruh data dan aset yang diberikan adalah akurat, lengkap, dan legal (memiliki hak penggunaan yang sah).\n•    **Dukungan Klien:** Klien wajib memberikan tanggapan atau persetujuan secara cepat pada tiap tahapan progres. Keterlambatan respons dari Klien dapat mengakibatkan mundurnya estimasi waktu penyelesaian tanpa menjadi tanggung jawab Kami.\n•    **Kerahasiaan Kredensial:** kredensial yang diberikan Klien (token, API key, akses admin) hanya digunakan untuk keperluan pengerjaan proyek dan tidak disimpan oleh Kami setelah proyek selesai, kecuali diperlukan untuk Dukungan Purnajual sesuai Pasal Dukungan dan Perawatan.\n## Batasan dan Larangan Layanan\nHarmony Hub berhak menolak atau membatalkan pesanan yang berkaitan dengan:\n•    **Pelanggaran ToS:** kegiatan yang melanggar Syarat dan Ketentuan platform pihak ketiga (seperti Discord, atau penyedia hosting).\n•    **Konten Terlarang:** konten atau tujuan yang bersifat ilegal (berdasarkan hukum Indonesia), pornografi, scam/penipuan, atau aktivitas yang merugikan pihak lain.\n•    **Pelanggaran HAKI:** pekerjaan yang melanggar Hak Kekayaan Intelektual pihak lain. Klien bertanggung jawab penuh atas segala tuntutan hukum yang timbul akibat konten yang disediakan oleh Klien.",
    ),
    haki_terms: createEmbed(
        "## Hak Penggunaan dan Lisensi\n•    **Pengalihan Hak:** Klien memperoleh hak penggunaan penuh dan permanen atas Karya Akhir (termasuk source code, aset digital, konfigurasi, dan desain) untuk keperluan operasional internal, berlaku efektif setelah pembayaran dilunasi secara tuntas (Pasal Ketentuan Pembayaran).\n•    **Pembatasan Distribusi:** kecuali disepakati lain secara tertulis, Karya Akhir ditujukan untuk penggunaan Klien. Penjualan kembali atau pendistribusian massal oleh Klien kepada pihak ketiga memerlukan lisensi tambahan sesuai kesepakatan.\n•    **Modifikasi Pihak Ketiga:** modifikasi kode oleh Klien atau pihak luar diperbolehkan, namun hal ini akan menghanguskan seluruh dukungan teknis (*support*) dan garansi dari Kami. Kami tidak bertanggung jawab atas kerusakan, kebocoran data, atau masalah fungsionalitas yang timbul akibat modifikasi yang dilakukan di luar pengawasan Kami.\n## Hak Orisinalitas Penyedia Jasa\nPenyedia Jasa mempertahankan hak untuk menggunakan kembali konsep, metodologi, dan teknik pemrograman non-spesifik yang bersifat umum dalam proyek lain, kecuali aset visual/identitas eksklusif milik Klien.",
    ),
    payment_terms: createEmbed(
        "## Metode Pembayaran\nPembayaran dilakukan melalui metode yang disediakan (Transfer Bank/E-Wallet) atau platform pihak ketiga yang disepakati.\n## Tahapan Penyerahan Karya Akhir\nKarya Akhir diserahkan dalam dua tahap:\n•    **Tahap Uji Coba:** Klien memperoleh akses demo/staging atau bukti fungsi (video, screen share, atau instance terbatas) untuk verifikasi bahwa Karya Akhir berfungsi sesuai SOW.\n•    **Tahap Penyerahan Penuh:** source code, kredensial produksi, dan akses penuh diserahkan hanya setelah pembayaran diterima secara tuntas.\nBatas waktu pelunasan: maksimal **1x24 jam** setelah Tahap Uji Coba disetujui Klien.\n## Keterlambatan Pembayaran\n•    Lewat **7 hari kalender** sejak jatuh tempo tanpa pelunasan, dikenakan denda keterlambatan sebesar **2% dari total nilai proyek per minggu** keterlambatan, dengan batas maksimal **10% (5 minggu)**.\n•    Selama periode keterlambatan, Tahap Penyerahan Penuh (Pasal Tahapan Penyerahan Karya Akhir) tetap ditahan dan tidak diberikan kepada Klien.\n•    Keterlambatan yang melampaui 5 minggu diproses sebagai sengketa pembayaran sesuai Pasal Penyelesaian Sengketa.\n## Kebijakan Harga\nKami berhak mengubah harga layanan umum sewaktu-waktu. Namun, harga dalam Penawaran Harga (*Quotation*) yang sudah disetujui bersifat final, tetap, dan mengikat hingga proyek selesai.",
    ),
    work_time: createEmbed(
        "## Perhitungan Waktu Pengerjaan\n•    **Mulai Pengerjaan:** estimasi waktu dihitung sejak Klien menyetujui SOW dan memberikan akses/informasi yang diperlukan secara lengkap.\n•    **Penyesuaian Jadwal:** waktu penyelesaian dapat berubah tergantung pada kompleksitas teknis, antrian proyek, atau Perubahan Scope di tengah jalan.\n•    **Hambatan Klien:** keterlambatan respons atau penyediaan aset dari sisi Klien akan secara otomatis memperpanjang estimasi waktu penyelesaian.\n## Penyerahan Karya Akhir\n•    **Kondisi Penyerahan:** Karya Akhir diserahkan dalam kondisi siap pakai (*ready-to-use*) setelah melalui tahap pengujian internal, sesuai tahapan pada Pasal Tahapan Penyerahan Karya Akhir.\n•    **Revisi:** Klien berhak atas 7 (tujuh) kali Revisi Minor (sesuai definisi Pasal Definisi Istilah Kunci) tanpa biaya tambahan, dalam jangka waktu 7 hari kalender setelah Tahap Uji Coba disetujui. Perbaikan kesalahan logika kode dari sisi Kami tidak termasuk dalam kuota ini dan ditangani tanpa batas jumlah selama masa garansi (Pasal Dukungan Purnajual Gratis).\n•    **Biaya Eksternal:** penyerahan Karya Akhir tidak mencakup biaya pihak ketiga seperti sewa hosting, pembelian domain, atau biaya berlangganan API lainnya.",
    ),
    cancellation_terms: createEmbed(
        "## Pembatalan oleh Klien\n•    **Sebelum Pengerjaan Dimulai:** pembatalan tanpa biaya, berlaku jika Penawaran Harga belum disetujui.\n•    **Setelah Penawaran Disetujui, Sebelum Kode Dibuat:** Klien dikenakan denda pembatalan sebesar 20% dari total nilai proyek sebagai biaya administrasi dan alokasi waktu.\n•    **Saat Pengerjaan Berlangsung:** Klien wajib membayar kompensasi secara proporsional sesuai dengan persentase progres pengerjaan yang telah dilakukan.\n## Pembatalan oleh Harmony Hub\n•    **Ketidaksanggupan Teknis:** Kami berhak membatalkan proyek secara sepihak jika dalam proses pengerjaan ditemukan kendala teknis yang sangat kompleks atau limitasi sistem yang membuat permintaan Klien tidak mungkin direalisasikan. Karena skema pembayaran Kami berbasis pelunasan di akhir (Pasal Ketentuan Pembayaran), pembatalan pada tahap ini tidak menimbulkan kewajiban finansial bagi Klien maupun Kami.\n•    **Pelanggaran oleh Klien:** Kami berhak menghentikan proyek secara sepihak jika Klien tidak kooperatif (tidak merespons dalam waktu wajar), gagal memberikan akses yang diperlukan, atau melanggar Pasal Batasan dan Larangan Layanan. Klien tetap wajib membayar kompensasi atas progres yang telah berjalan.\n## Batas Tanggung Jawab\nTotal kompensasi atau ganti rugi yang dapat dituntut dari Kami sehubungan dengan layanan ini, dalam bentuk apa pun, dibatasi maksimal sebesar total nilai Penawaran Harga yang telah dibayarkan Klien untuk proyek terkait.",
    ),
    support_maintenance: createEmbed(
        "## Dukungan Purnajual Gratis (Garansi)\n•    **Masa Garansi:** Kami memberikan garansi perbaikan bug (bug fixing) selama 7 (tujuh) hari kalender setelah Tahap Penyerahan Penuh. Garansi hanya berlaku untuk kesalahan logika kode dari sisi Kami.\n•    **Pengecualian Garansi:** garansi TIDAK berlaku untuk masalah yang disebabkan oleh perubahan API pihak ketiga (Discord/Platform/dll), gangguan pada penyedia hosting Klien, atau modifikasi kode yang dilakukan sendiri oleh Klien (sesuai Pasal Hak Penggunaan dan Lisensi).\n•    Konsultasi Dasar: Kami menyediakan panduan penggunaan dasar melalui Discord untuk memastikan Klien memahami operasional Karya Akhir.\n## Layanan Perawatan Berbayar\nSegala bentuk dukungan di luar cakupan garansi akan dikenakan biaya tambahan (*chargeable service*), yang meliputi:\n•    **Pengembangan Fitur:** penambahan fungsi baru atau perubahan desain signifikan setelah proyek dinyatakan selesai.\n•    **Update Kompatibilitas**: penyesuaian kode agar tetap berfungsi mengikuti pembaruan platform pihak ketiga di masa mendatang.\n•    **Dukungan Prioritas:** layanan bantuan dengan waktu respons yang lebih cepat serta penanganan teknis prioritas.",
    ),
    dispute_resolution: createEmbed(
        "## Prosedur Penyelesaian Awal\n•    **Komunikasi Awal:** setiap masalah, keluhan, atau sengketa yang timbul sehubungan dengan layanan harus disampaikan terlebih dahulu melalui saluran komunikasi resmi Kami, yaitu melalui kanal Discord <#1251433206914486343> atau kontak email resmi.\n•    **Komitmen Respon:** Kami berkomitmen untuk merespons setiap keluhan secara wajar dalam waktu 1x24 jam kalender sejak keluhan diterima.\n•    **Musyawarah:** kedua belah pihak setuju untuk mencari solusi yang adil melalui musyawarah mufakat dan itikad baik (*good faith*) sebelum menempuh jalur hukum formal.\n## Hukum dan Yurisdiksi\n•    **Hukum yang Berlaku:** Syarat dan Ketentuan ini tunduk pada dan ditafsirkan sesuai dengan hukum yang berlaku di Republik Indonesia.\n•    **Penyelesaian Hukum:** jika sengketa tidak dapat diselesaikan melalui musyawarah dalam jangka waktu 30 (tiga puluh) hari kalender, maka sengketa tersebut akan diselesaikan melalui jalur hukum pada yurisdiksi yang berlaku di wilayah hukum Pengadilan Negeri Bandung.",
    ),
    tos_changes: createEmbed(
        "•    **Hak Perubahan:** Harmony Hub berhak untuk merevisi, memodifikasi, atau menambahkan ketentuan baru pada S&K ini sewaktu-waktu guna mengikuti perkembangan layanan atau regulasi yang berlaku.\n•    **Pemberlakuan:** setiap perubahan akan berlaku efektif sejak tanggal dipublikasikan pada saluran komunikasi resmi (Server Discord).\n•    **Kewajiban Klien:** Klien bertanggung jawab untuk meninjau S&K ini secara berkala. Penggunaan layanan yang berlanjut setelah perubahan dipublikasikan dianggap sebagai persetujuan penuh terhadap versi terbaru.\n•    **Proyek Berjalan:** untuk proyek yang sedang dalam tahap pengerjaan, versi S&K yang berlaku adalah versi yang disetujui pada saat Penawaran Harga (*Quotation*) disetujui, kecuali terdapat perubahan yang bersifat mendesak demi keamanan sistem.",
    ),
    official_contact: createEmbed(
        "Untuk pertanyaan, klarifikasi, atau pengajuan keluhan terkait layanan, Klien dapat menghubungi Kami melalui saluran berikut:\n•    **Discord Resmi:** kanal <#1251433206914486343> di server Harmony Hub.\n•    **Email Resmi:** harmonyhub.id@gmail.com\n•    **Waktu Respons:** Kami berkomitmen memberikan tanggapan atau konfirmasi penerimaan pesan dalam waktu maksimal 1x24 jam kalender.",
    ),
    closing: createEmbed(
        "## Klausul Keterikatan dan Persetujuan\nDengan menggunakan layanan Harmony Hub, melakukan pemesanan, atau melakukan pembayaran, Anda dianggap telah membaca, memahami, dan menyetujui seluruh Syarat dan Ketentuan di atas.\n\nDokumen ini merupakan perjanjian yang dibuat untuk melindungi kepentingan kedua belah pihak dan memastikan kualitas layanan yang optimal.\n\n**Informasi Pembaruan Dokumen:** Rancangan ini disusun pada 24 Juli 2026, menggantikan versi 10 Mei 2026.",
    ),
};

function handleToSSelect(interaction) {
    const selectedValue = interaction.data?.values?.[0];
    const embed = Object.hasOwn(tosEmbeds, selectedValue) ? tosEmbeds[selectedValue] : undefined;

    if (embed) return ephemeralEmbed([embed]);

    return ephemeralEmbed([
        {
            color: config.color.default,
            description: "Pilihan ini belum tersedia.",
        },
    ]);
}

export const tosComponentHandlers = {
    tos_select_menu: handleToSSelect,
};
